export enum CurriculumDiagramType {
  DEFAULT = "default",
  DOT = "dot",
  NONE = "none",
}

export enum CurriculumDndType {
  DND_BY_YEAR = "dnd_by_year",
  DND_BY_COURSE_RELATIONSHIP = "dnd_by_course_relationship",
}

export enum CurriculumCommandType {
  ADD_COURSE_RELATIONSHIP = "ADD_COURSE_RELATIONSHIP",
  REMOVE_COURSE_RELATIONSHIP = "REMOVE_COURSE_RELATIONSHIP",
  CHANGE_COURSE_RELATIONSHIP = "CHANGE_COURSE_RELATIONSHIP",
  ADD_COURSES_TO_SEMESTER = "ADD_COURSES_TO_SEMESTER",
  REMOVE_COURSE_FROM_SEMESTER = "REMOVE_COURSE_FROM_SEMESTER",
  CHANGE_COURSE_BETWEEN_TWO_SEMESTER = "CHANGE_COURSE_BETWEEN_TWO_SEMESTER",
  CHANGE_YEAR_ORDER = "CHANGE_YEAR_ORDER",
  ADD_YEAR = "ADD_YEAR",
  REMOVE_YEAR = "REMOVE_YEAR",
}
